### ISSUE TITLE
wooting_rgb_reset allows no further Commands afterwards

### ISSUE THREAD

**Issue by N00byKing** [WootingKb/wooting-rgb-sdk#16]
When issuing `wooting_rgb_reset()`, all further color-change commands are ignored.
Is this intended ? (It wasn't the case before).

I am using a Wooting One

EDIT: Additionally, not running `wooting_rgb_kbd_connected()` on start will also let all changes fail silently

**Comment by simon-wh** [comment]
Just pushed some changes which should hopefully resolve your issues. Could you give them a wee test for me? Just on the [develop branch](https://github.com/WootingKb/wooting-rgb-sdk/tree/develop).

Also, what is your use case for applying lighting after calling `wooting_rgb_reset()`? As the reset function also closes the keyboard, so it may be worthwhile splitting the function into `wooting_rgb_colors_reset` and `wooting_rgb_close`?

**Comment by N00byKing** [comment]
I have a Program that plays a lil' animation when I lock my Computer. I want the Keyboard to function normally before and after locking (the program runs as a background service). Therefore, I call reset after an unlock (and new changes wont be applied after relock etc.).

I have another Program that does lighting effects for a Game and displays stats on the keyboard. That one's pretty recent and therefore probably broken though ᵖˡˢ ᵃᵘʳᵒʳᵃ , but it encounters the same issue: After closing the Game and reopening, color changes fail.

Generally this is probably (?) an issue with any Background Service using the SDK. 

I think your suggestion in splitting them is the best course of action, imo.

Sadly I can't test the branch at the moment. I'll try to next Tuesday at the latest (currently away)

**Comment by N00byKing** [comment]
Tested it, the fix works great!

**Comment by N00byKing** [comment]
Sorry, but were the changes merged yet?

**Comment by PastaJ36** [comment]
You're right, woops

**Comment by simon-wh** [comment]
I've pushed an initial version of the separate "Reset RGB" function in the develop branch if you wanna have a wee play around with it @N00byKing

**Comment by N00byKing** [comment]
Will do as soon as I can. Sadly I am seperated from my Keyboard for a while ._.

**Comment by Rocky04** [comment]
The initial method was that only by sending `RgbColorInit` the keyboard is allowed to change the colours externally and ignoring everything when not and this mode is leaved by the `RgbColorResetAll` command. So the behaviour was expected from me. To me it looks like there isn't a real concept here. Despite the bug, that now a RGB command can put the Wooting into a deadloop or something when sent after the RGB mode is leaved, a clear handling is missing. Like the keyboard should inform the app with a status message as a reply if it don't accept RGB updates because it's not in the RGB mode, then the app knows that it must send the init command again. Next the init command can have a paramter to control if every LED should be set back to default. So the app can reset every key without the need to leave the mode or to have a new command just for that. In addition an app has the choice to not influence the keys it don't take care of. Then it's possible to use multiple apps for different keys without interfering each other.

The main problem here is that multiple apps can change the LEDs instead that only one has the main control and decides which app can change it (like a priority list). By this you can also block specific apps (maybe not all future apps are nice). Like how the Razer Connect feature works. Like I would love to see the ability to exclude different keys in the Wootility from external RGB controlling. So that the mode key always have the colour which is set for the specific profile.

**Comment by N00byKing** [comment]
Well, I finally tested it (sorry about the Delay, Corona seperated me from my Keyboard).

It _seems_ to work fine.

However, in one of my Programs it now hard-crashes the Keyboard for some reason. I really have no clue why. I tried making a smaller Program to illustrate the Issue, but I was not able to (If you want to take a look, its [ŧhis one](https://github.com/N00byKing/wootlock)).

Otherwise LGTM

**Comment by simon-wh** [comment]
@N00byKing The keyboard hard crash issue should be resolved with the improvements to the RGB interface in the firmware we're working as I referred to in the other issue. I'll try to remember to let you know when we've pushed that firmware update so you can take it for a spin
