### ISSUE TITLE
Move hid_write calls to a separate thread

### ISSUE THREAD

**Issue by codecat** [WootingKb/wooting-rgb-sdk#17]
So, it turns out that calling `hid_write` takes a long time in the Wooting RGB SDK, which results in `wooting_rgb_array_update_keyboard` blocking for quite a while.

It would be nice if the hid write calls were separate in another thread, so application developers don't have to worry about multithreading.

**Comment by PastaJ36** [comment]
Thanks for the feedback. I think we want to keep the RGB SDK single threaded, because conceptually you only want one update at the time running to your keyboard. If the application has a specific use case that cannot have blocking calls I think the application should be the one handling the threads. 

I'm closing this issue. Feel free to re-open if the time you measure is unnecessarily long, that's an issue we can fix.
